server:
 port: 8001
 
mybatis:
    config-location: classpath:mybatis/mybatis.cfg.xml
    type-aliases-package: com.hq.entity
    mapper-locations: 
    - classpath:mybatis/mapper/**/*.xml
    
spring:
    application:
        name: hqcloud-club
    datasource:
    # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hqcloud_club?useUnicode=true&characterEncoding=UTF8
      username: root
      password: 123456
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20